# Generated by Django 4.0 on 2021-12-20 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('city', models.CharField(choices=[('SJ', 'San Jose'), ('SF', 'San Francisco'), ('OAKLAND', 'Oakland'), ('FREMONT', 'Fremont'), ('SR', 'Santa Rosa'), ('HAYWARD', 'Hayward'), ('PALO ALTO', 'Palo Alto'), ('SV', 'Sunnyvale'), ('SC', 'Santa Clara'), ('VALLEJO', 'Vallejo'), ('CONCORD', 'Concord'), ('BERKELEY', 'Berkeley'), ('SM', 'San Mateo'), ('MV', 'Mountain View'), ('SR', 'San Rafael'), ('RICHMOND', 'Richmond')], max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('place', models.CharField(choices=[('SR', 'Shared room'), ('PR', 'Private room'), ('EP', 'Entire place')], max_length=10)),
                ('image1', models.TextField()),
                ('image2', models.TextField()),
                ('image3', models.TextField()),
                ('image4', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.user')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=200)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.user')),
            ],
        ),
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wifi', models.BooleanField(default=False)),
                ('kitchen', models.BooleanField(default=False)),
                ('washer', models.BooleanField(default=False)),
                ('gym', models.BooleanField(default=False)),
                ('bike', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('cctv', models.BooleanField(default=False)),
                ('gate', models.BooleanField(default=False)),
                ('wifi_bill', models.IntegerField(default=False)),
                ('water_bill', models.IntegerField(default=False)),
                ('electricity_bill', models.IntegerField(default=False)),
                ('gas_bill', models.IntegerField(default=False)),
                ('heating_bill', models.IntegerField(default=False)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.property')),
            ],
        ),
    ]
