# Generated by Django 4.0 on 2021-12-20 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_property_booking_amenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(choices=[('BERKELEY', 'Berkeley'), ('CONCORD', 'Concord'), ('FREMONT', 'Fremont'), ('HAYWARD', 'Hayward'), ('MV', 'Mountain View'), ('OAKLAND', 'Oakland'), ('PALO ALTO', 'Palo Alto'), ('RICHMOND', 'Richmond'), ('SC', 'Santa Clara'), ('SJ', 'San Jose'), ('SF', 'San Francisco'), ('SM', 'San Mateo'), ('SR', 'San Rafael'), ('SR', 'Santa Rosa'), ('SV', 'Sunnyvale'), ('VALLEJO', 'Vallejo')], max_length=50),
        ),
    ]
