# Generated by Django 3.2.8 on 2021-11-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bids_listings'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='image',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='listings',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
